version: '3.7'

volumes:
  ckan_config:
  ckan_home:
  ckan_storage:
  db_data:
  solr_data:
  redis-data:
  pgadmin-data:

services:
  ckan:
    build: ckan
    links:
      - db
      - solr
      - redis
      - datapusher
      - smtp
      - dbadmin
    depends_on:
      - db
      - solr
    ports:
      - "0.0.0.0:80:80"
    environment:
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800
      - CKAN_SITE_URL=http://ckan:${CKAN_PORT}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
    volumes:
      - ckan_config:/etc/ckan
      - ckan_home:/usr/lib/ckan
      - ckan_storage:/var/lib/ckan
      - ./ckan/production.ini:/etc/ckan/default/production.ini
      - ./ckan/who.ini:/etc/ckan/default/who.ini

  datapusher:
    image: clementmouchet/datapusher
    ports:
      - "8800:8800"

  db:
    build: postgresql
    environment:
      - POSTGRES_DB=ckan
      - POSTGRES_USER=ckan
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  solr:
    build: solr
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data
    ports:
      - "8983:8983"

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

  smtp:
    image: schickling/mailcatcher
    ports:
      - "18180:1080"

  dbadmin:
    image: dpage/pgadmin4:4.20
    ports:
      - 8480:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ckan
      PGADMIN_DEFAULT_PASSWORD: ckan
    links:
      - db
    restart: always